### ISSUE TITLE
Estructura de Sistema

### ISSUE THREAD

**Issue by JonDotsoy** [tdoee/Appbase#1]
![image](https://cloud.githubusercontent.com/assets/3086539/15919612/65964d76-2de9-11e6-9358-0d380bca13e0.png)
- [x] Appdata
  - [x] VERSION (commit c7a7237be65f25409a43c7a949b9b487ad3de951)
- [x] Session
- [x] Reference
- [x] Transport
- [x] Database
- [x] Auth

**Comment by JonDotsoy** [comment]
```
> appbase@0.0.0 test Appbase
> jasmine

Started
..F

Failures:
1) Carga 'Appbase' Load version number...
  Message:
    TypeError: Invalid Version: undefined
  Stack:
    TypeError: Invalid Version: undefined
        at new SemVer (Appbase\node_modules\semver\semver.js:279:11)
        at compare (Appbase\node_modules\semver\semver.js:566:10)
        at Function.eq (Appbase\node_modules\semver\semver.js:605:10)
        at Object.<anonymous> (Appbase.spec.js:19:18)

3 specs, 1 failure
Finished in 0.059 seconds
```

**Comment by JonDotsoy** [comment]
Error:

``` js
import { appbaseSymbol } from '../Appbase'
```

Fix

``` js
import { appbaseSymbol } from './Appbase'
```
